# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Sep  9 16:58:27 2025
# ------------------------------------------------

package:
  name: bzip2
  version: 1.0.8
source:
  url: https://gitlab.com/bzip2/bzip2/-/archive/bzip2-1.0.8/bzip2-bzip2-1.0.8.tar.gz
  sha256: db106b740252669664fd8f3a1c69fe7f689d5cd4b132f82ba82b9afba27627df
  patches:
    - patches/0001-cross.patch
    - patches/0002-Windows-Make-library-name-lowercase.patch
    - patches/0003-Windows-Add-dyn-lib-build-rename-libbz2_static.patch
build:
  number: '8'
  run_exports:
    - bzip2 >=1.0.8,<2.0a0
  string: hda65f42_8
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 h4bf12b8_1
    - binutils_linux-64 2.44 h4852527_1
    - gcc_impl_linux-64 14.3.0 hd9e9e21_5
    - gcc_linux-64 14.3.0 h1382650_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 h1423503_1
    - libgcc 15.1.0 h767d61c_5
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_105
    - libgomp 15.1.0 h767d61c_5
    - libsanitizer 14.3.0 hd08acf3_5
    - libstdcxx 15.1.0 h8f9b012_5
    - make 4.4.1 hb9d3cd8_2
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_5
    - libgomp 15.1.0 h767d61c_5
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
test:
  commands:
    - bzip2 --help
    - test -f ${PREFIX}/bin/bunzip2
    - test -f ${PREFIX}/bin/bzcat
    - test -f ${PREFIX}/bin/bzcmp
    - test -f ${PREFIX}/bin/bzdiff
    - test -f ${PREFIX}/bin/bzegrep
    - test -f ${PREFIX}/bin/bzfgrep
    - test -f ${PREFIX}/bin/bzgrep
    - test -f ${PREFIX}/bin/bzip2recover
    - test -f ${PREFIX}/bin/bzip2
    - test -f ${PREFIX}/bin/bzless
    - test -f ${PREFIX}/bin/bzmore
    - test -f ${PREFIX}/include/bzlib.h
    - test -f ${PREFIX}/lib/libbz2.a
    - test -f ${PREFIX}/lib/libbz2.so
about:
  home: https://gitlab.com/bzip2/bzip2
  license_family: BSD
  license_file: LICENSE
  license: bzip2-1.0.6
  summary: high-quality data compressor
  description: 'Bzip2 is a freely available high-quality data compressor. It typically

    compresses files to within 10% to 15% of the best available techniques,

    whilst being around twice as fast at compression and six times faster

    at decompression.

    '
  dev_url: https://gitlab.com/bzip2/bzip2
extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
    - msarahan
    - pelson
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250909.4.1
  remote_url: https://github.com/conda-forge/bzip2-feedstock
  sha: c19f23038caf2145a010d20e20514a2d4dd8f896
