# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Oct 13 15:32:09 2025
# ------------------------------------------------

package:
  name: fmt
  version: 12.0.0
source:
  url: https://github.com/fmtlib/fmt/archive/12.0.0.tar.gz
  sha256: aa3e8fbb6a0066c03454434add1f1fc23299e85758ceec0d7d2d974431481e40
build:
  number: '0'
  run_exports:
    - fmt >=12.0.0,<12.1.0a0
  string: h2b0788b_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - bzip2 1.0.8 hda65f42_8
    - c-ares 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - cmake 4.1.2 hc85cc9f_0
    - gcc_impl_linux-64 14.3.0 hd9e9e21_7
    - gcc_linux-64 14.3.0 h298d278_12
    - gxx_impl_linux-64 14.3.0 he663afc_7
    - gxx_linux-64 14.3.0 h95f728e_12
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libcurl 8.14.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.1 hecca717_0
    - libgcc 15.2.0 h767d61c_7
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_107
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libnghttp2 1.67.0 had1ee68_0
    - libsanitizer 14.3.0 hd08acf3_7
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.2.0 h8f9b012_7
    - libstdcxx-devel_linux-64 14.3.0 h85bb3a7_107
    - libstdcxx-ng 15.2.0 h4852527_7
    - libuv 1.51.0 hb03c661_1
    - libzlib 1.3.1 hb9d3cd8_2
    - make 4.4.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.4 h26f9b46_0
    - rhash 1.4.6 hb9d3cd8_1
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.2.0 h767d61c_7
    - libgomp 15.2.0 h767d61c_7
    - libstdcxx 15.2.0 h8f9b012_7
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - libstdcxx >=14
test:
  commands:
    - test -d ${PREFIX}/include/fmt
    - test -f ${PREFIX}/include/fmt/core.h
    - test -f ${PREFIX}/include/fmt/format.h
    - test -f ${PREFIX}/lib/cmake/fmt/fmt-config.cmake
    - test -f ${PREFIX}/lib/libfmt.so
  downstreams:
    - libmambapy
about:
  home: https://fmt.dev/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '{fmt} is an open-source formatting library for C++'
  description: '{fmt} is an open-source formatting library for C++.

    It can be used as a safe and fast alternative to (s)printf and iostreams.

    '
  doc_url: https://fmt.dev/latest/
  dev_url: https://github.com/fmtlib/fmt
extra:
  recipe-maintainers:
    - bdice
    - h-vetinari
    - saraedum
    - tdegeus
    - vitaut
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251013.1.1
  remote_url: https://github.com/conda-forge/fmt-feedstock
  sha: f88e8807d167f7084616f716bfd303f63877a0f6
