# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug 24 15:04:17 2025
# ------------------------------------------------

package:
  name: frozendict
  version: 2.4.6
source:
  fn: frozendict-2.4.6.tar.gz
  url: https://pypi.org/packages/source/f/frozendict/frozendict-2.4.6.tar.gz
  sha256: df7cd16470fbd26fc4969a208efadc46319334eb97def1ddf48919b351192b8e
build:
  script: python -m pip install . --no-deps -vv
  number: '1'
  string: py312h4c3975b_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 h4bf12b8_1
    - binutils_linux-64 2.44 h4852527_1
    - gcc_impl_linux-64 14.3.0 hd9e9e21_4
    - gcc_linux-64 14.3.0 h1382650_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 h1423503_1
    - libgcc 15.1.0 h767d61c_4
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_104
    - libgomp 15.1.0 h767d61c_4
    - libsanitizer 14.3.0 hd08acf3_4
    - libstdcxx 15.1.0 h8f9b012_4
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - ld_impl_linux-64 2.44 h1423503_1
    - libexpat 2.7.1 hecca717_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_4
    - libgcc-ng 15.1.0 h69a702a_4
    - libgomp 15.1.0 h767d61c_4
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.4 h0c1763c_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.2 h26f9b46_0
    - pip 25.2 pyh8b19718_0
    - python 3.12.11 h9e4cc4f_0_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  imports:
    - frozendict
about:
  home: https://github.com/Marco-Sulla/python-frozendict
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An immutable dictionary
  dev_url: https://github.com/Marco-Sulla/python-frozendict
extra:
  recipe-maintainers:
    - Marco-Sulla
    - ltalirz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250824.2.1
  remote_url: https://github.com/conda-forge/frozendict-feedstock
  sha: b84745d01b1f2d47effe1c82a0c1637dc07efba9
