# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Sep 13 06:22:49 2025
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.6
source:
  url: https://github.com/conda/pycosat/archive/0.6.6.tar.gz
  sha256: b0014986321e77a36d8fe24827698aae076500c817133a700608bd677b77a998
  patches:
    - patches/0001-GH-100-Replace-unittest.makeSuite-with-unittest.defaultTest.patch
build:
  number: '3'
  script: /home/conda/feedstock_root/build_artifacts/pycosat_1757744639790/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps -vv
  string: py312h4c3975b_3
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 h4bf12b8_1
    - binutils_linux-64 2.44 h4852527_1
    - gcc_impl_linux-64 14.3.0 hd9e9e21_5
    - gcc_linux-64 14.3.0 h1382650_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 h1423503_1
    - libgcc 15.1.0 h767d61c_5
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_105
    - libgomp 15.1.0 h767d61c_5
    - libsanitizer 14.3.0 hd08acf3_5
    - libstdcxx 15.1.0 h8f9b012_5
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - ld_impl_linux-64 2.44 h1423503_1
    - libexpat 2.7.1 hecca717_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_5
    - libgcc-ng 15.1.0 h69a702a_5
    - libgomp 15.1.0 h767d61c_5
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.4 h0c1763c_0
    - libuuid 2.41.1 he9a06e4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.2 h26f9b46_0
    - pip 25.2 pyh8b19718_0
    - python 3.12.11 h9e4cc4f_0_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  requires:
    - pip
  imports:
    - pycosat
  commands:
    - pip check
    - python test_package.py "0.6.6"
about:
  home: https://github.com/conda/pycosat
  license: MIT
  license_file:
    - COPYRIGHT
    - LICENSE
  summary: Bindings to picosat (a SAT solver)
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  doc_url: https://pypi.python.org/pypi/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  dev_url: https://github.com/conda/pycosat
extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - nehaljwani
    - pelson
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250913.1.1
  remote_url: https://github.com/conda-forge/pycosat-feedstock
  sha: 42d6b5b0a2382e83eef2e4ba12b519a151386102
