# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 15 21:35:17 2025
# ------------------------------------------------

package:
  name: ruamel.yaml.clib
  version: 0.2.14
source:
  - url: https://pypi.org/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-0.2.14.tar.gz
    sha256: 803f5044b13602d58ea378576dd75aa759f52116a0232608e8fdada4da33752e
build:
  number: '0'
  script:
    - cythonize _ruamel_yaml.pyx
    - /home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1760564169582/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m pip install . -vv
  string: py312h4c3975b_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - gcc_impl_linux-64 14.3.0 hd9e9e21_7
    - gcc_linux-64 14.3.0 h298d278_12
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libgcc 15.2.0 h767d61c_7
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_107
    - libgomp 15.2.0 h767d61c_7
    - libsanitizer 14.3.0 hd08acf3_7
    - libstdcxx 15.2.0 h8f9b012_7
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - cython 3.1.4 py312h7c45ced_2
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libexpat 2.7.1 hecca717_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.4 h0c1763c_0
    - libstdcxx 15.2.0 h8f9b012_7
    - libuuid 2.41.2 he9a06e4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.4 h26f9b46_0
    - pip 25.2 pyh8b19718_0
    - python 3.12.12 hfe2f287_0_cpython
    - python_abi 3.12 8_cp312
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  downstreams:
    - ruamel.yaml
  commands:
    - python -c "from importlib.util import find_spec; assert find_spec('_ruamel_yaml')"
about:
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml
extra:
  recipe-maintainers:
    - mbargull
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251015.5.1
  remote_url: https://github.com/conda-forge/ruamel.yaml.clib-feedstock
  sha: 40dda58d8db19df7fd7633c70461badf9efe3ae0
