# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Oct 10 15:02:01 2025
# ------------------------------------------------

package:
  name: conda
  version: 25.9.1
source:
  fn: conda-25.9.1.tar.gz
  url: https://github.com/conda/conda/releases/download/25.9.1/conda-25.9.1.tar.gz
  sha256: afb3cc2393a6a05afbc37420bebdd8d23198da35f079c234aa05fedf042745dd
  folder: conda-src
build:
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/conda_1760108593422/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install conda-src/ --no-deps --no-build-isolation -vv && /home/conda/feedstock_root/build_artifacts/conda_1760108593422/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m conda init --install
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  string: py312h7900ff3_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - boltons 25.0.0 pyhd8ed1ab_0
    - brotli-python 1.1.0 py312h1289d80_4
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - certifi 2025.10.5 pyhd8ed1ab_0
    - cffi 2.0.0 py312h35888ee_0
    - charset-normalizer 3.4.3 pyhd8ed1ab_0
    - colorama 0.4.6 pyhd8ed1ab_1
    - editables 0.5 pyhd8ed1ab_1
    - frozendict 2.4.6 py312h4c3975b_1
    - h2 4.3.0 pyhcf101f3_0
    - hatch-vcs 0.5.0 pyhd8ed1ab_0
    - hatchling 1.27.0 pypyhd8ed1ab_0
    - hpack 4.1.0 pyhd8ed1ab_0
    - hyperframe 6.1.0 pyhd8ed1ab_0
    - idna 3.10 pyhd8ed1ab_1
    - importlib-metadata 8.7.0 pyhe01879c_1
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libexpat 2.7.1 hecca717_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.4 h0c1763c_0
    - libstdcxx 15.2.0 h8f9b012_7
    - libuuid 2.41.2 he9a06e4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - menuinst 2.3.1 py312h7900ff3_1
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.4 h26f9b46_0
    - packaging 25.0 pyh29332c3_1
    - pathspec 0.12.1 pyhd8ed1ab_1
    - pip 25.2 pyh8b19718_0
    - platformdirs 4.5.0 pyhcf101f3_0
    - pluggy 1.6.0 pyhd8ed1ab_0
    - pycparser 2.22 pyh29332c3_1
    - pysocks 1.7.1 pyha55dd90_7
    - python 3.12.11 h9e4cc4f_0_cpython
    - python_abi 3.12 8_cp312
    - readline 8.2 h8c095d6_2
    - requests 2.32.5 pyhd8ed1ab_0
    - ruamel.yaml 0.18.15 py312h4c3975b_1
    - ruamel.yaml.clib 0.2.12 py312h4c3975b_1
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 9.2.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_hd72426e_102
    - tomli 2.3.0 pyhcf101f3_0
    - tqdm 4.67.1 pyhd8ed1ab_1
    - trove-classifiers 2025.9.11.17 pyhd8ed1ab_0
    - typing-extensions 4.15.0 h396c80c_0
    - typing_extensions 4.15.0 pyhcf101f3_0
    - tzdata 2025b h78e105d_0
    - urllib3 2.5.0 pyhd8ed1ab_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.23.0 pyhd8ed1ab_0
    - zstandard 0.25.0 py312h5253ce2_0
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - archspec >=0.2.3
    - boltons >=23.0.0
    - charset-normalizer
    - conda-libmamba-solver >=25.4.0
    - conda-package-handling >=2.2.0
    - distro >=1.5.0
    - frozendict >=2.4.2
    - jsonpatch >=1.32
    - menuinst >=2
    - packaging >=23.0
    - platformdirs >=3.10.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
    - requests >=2.28.0,<3
    - ruamel.yaml >=0.11.14,<0.19
    - setuptools >=60.0.0
    - tqdm >=4
    - truststore >=0.8.0
    - zstandard >=0.19.0
  run_constrained:
    - conda-build >=25.9
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
test:
  requires:
    - mock
    - pexpect
    - responses
  imports:
    - conda
    - conda_env
  files:
    - commands_to_test.sh
    - test_runner.sh
  downstreams:
    - conda-smithy
about:
  home: https://conda.io
  license: BSD-3-Clause
  license_file: conda-src/LICENSE
  summary: OS-agnostic, system-level binary package and environment manager.
  description: 'Conda is an open source package management system and environment

    management system for installing multiple versions of software packages

    and their dependencies and switching easily between them. It works on

    Linux, OS X and Windows, and was created for Python programs but can

    package and distribute any software.

    '
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  dev_url: https://github.com/conda/conda
extra:
  recipe-maintainers:
    - beeankha
    - dbast
    - isuruf
    - jakirkham
    - jezdez
    - kenodegard
    - mbargull
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251010.2.1
  remote_url: https://github.com/conda-forge/conda-feedstock
  sha: 42af4adfffd76fce3c22351022604ed65c0a61c1
