# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Oct 24 09:54:27 2025
# ------------------------------------------------

package:
  name: menuinst
  version: 2.4.1
source:
  url: https://github.com/conda/menuinst/archive/2.4.1.tar.gz
  sha256: dc656f0f5a85d7e282a869e0e771e7fdab112a54ce95aabe78849dc90fec0f83
build:
  number: '0'
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION=2.4.1
  script:
    - rm -f "/home/conda/feedstock_root/build_artifacts/menuinst_1761299738838/work/menuinst/data/osx_launcher_*"
    - rm -f "/home/conda/feedstock_root/build_artifacts/menuinst_1761299738838/work/menuinst/data/appkit_launcher_*"
    - /home/conda/feedstock_root/build_artifacts/menuinst_1761299738838/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install . -vv
  entry_points:
    - menuinst = menuinst.cli:main
  string: py312h7900ff3_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - importlib-metadata 8.7.0 pyhe01879c_1
    - ld_impl_linux-64 2.44 h1aa0949_3
    - libexpat 2.7.1 hecca717_0
    - libffi 3.5.2 h9ec8514_0
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.4 h0c1763c_0
    - libstdcxx 15.2.0 h8f9b012_7
    - libuuid 2.41.2 he9a06e4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.4 h26f9b46_0
    - packaging 25.0 pyh29332c3_1
    - pip 25.2 pyh8b19718_0
    - python 3.12.12 hd63d673_1_cpython
    - readline 8.2 h8c095d6_2
    - setuptools 80.9.0 pyhff2d567_0
    - setuptools-scm 9.2.2 pyhd8ed1ab_0
    - setuptools_scm 9.2.2 hd8ed1ab_0
    - tk 8.6.13 noxft_hd72426e_102
    - tomli 2.3.0 pyhcf101f3_0
    - typing-extensions 4.15.0 h396c80c_0
    - typing_extensions 4.15.0 pyhcf101f3_0
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
    - zipp 3.23.0 pyhd8ed1ab_0
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
test:
  imports:
    - menuinst
    - menuinst.api
  commands:
    - menuinst --help
about:
  home: https://github.com/conda/menuinst/
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE.txt
    - menuinst/_vendor/apipkg/LICENSE
  summary: cross platform install of menu items
  doc_url: https://conda.github.io/menuinst/
extra:
  recipe-maintainers:
    - carlodri
    - goanpeca
    - isuruf
    - jaimergp
    - jakirkham
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251024.1.1
  remote_url: https://github.com/conda-forge/menuinst-feedstock
  sha: b222b5493e1d6ed6671ff440e4d30363609ed0b5
