# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.50.4
source:
  url: https://www.sqlite.org/2025/sqlite-autoconf-3500400.tar.gz
  sha256: a3db587a1b92ee5ddac2f66b3edb41b26f9c867275782d46c3a088977d6a5b18
build:
  run_exports:
    - libsqlite >=3.50.4,<4.0a0
  number: 0
  string: h0c1763c_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 h4bf12b8_1
    - binutils_linux-64 2.44 h4852527_1
    - gcc_impl_linux-64 14.3.0 hd9e9e21_4
    - gcc_linux-64 14.3.0 h1382650_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 h1423503_1
    - libgcc 15.1.0 h767d61c_4
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_104
    - libgomp 15.1.0 h767d61c_4
    - libsanitizer 14.3.0 hd08acf3_4
    - libstdcxx 15.1.0 h8f9b012_4
    - make 4.4.1 hb9d3cd8_2
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_4
    - libgomp 15.1.0 h767d61c_4
    - libzlib 1.3.1 hb9d3cd8_2
    - zlib 1.3.1 hb9d3cd8_2
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - libzlib >=1.3.1,<2.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
    - test -f $PREFIX/lib/pkgconfig/sqlite3.pc
about:
  home: http://www.sqlite.org/
  license: blessing
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  doc_url: http://www.sqlite.org/docs.html
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  dev_url: https://github.com/mackyle/sqlite
extra:
  recipe-maintainers:
    - flaviomartins
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250731.2.1
  remote_url: https://github.com/conda-forge/sqlite-feedstock
  sha: b6864257cc3702ab9900b9c476285c5c0aa1bac1
