# This file created by conda-build 25.7.0
# ------------------------------------------------

package:
  name: simdjson
  version: 4.0.7
source:
  url: https://github.com/simdjson/simdjson/archive/v4.0.7.tar.gz
  sha256: d2d15490605858d3dd42e90d25e0fde31c53446b7d3cde9ef334449236927916
build:
  run_exports:
    - simdjson >=4.0.7,<4.1.0a0
  number: 0
  string: hb700be7_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - bzip2 1.0.8 hda65f42_8
    - c-ares 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - cmake 4.1.1 hc85cc9f_0
    - gcc_impl_linux-64 14.3.0 hd9e9e21_5
    - gcc_linux-64 14.3.0 h1382650_11
    - gxx_impl_linux-64 14.3.0 he663afc_5
    - gxx_linux-64 14.3.0 ha7acb78_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libcurl 8.14.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.1 hecca717_0
    - libgcc 15.1.0 h767d61c_5
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_105
    - libgcc-ng 15.1.0 h69a702a_5
    - libgomp 15.1.0 h767d61c_5
    - liblzma 5.8.1 hb9d3cd8_2
    - libnghttp2 1.67.0 had1ee68_0
    - libsanitizer 14.3.0 hd08acf3_5
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.1.0 h8f9b012_5
    - libstdcxx-devel_linux-64 14.3.0 h85bb3a7_105
    - libstdcxx-ng 15.1.0 h4852527_5
    - libuv 1.51.0 hb03c661_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - ninja 1.13.1 h171cf75_0
    - openssl 3.5.3 h26f9b46_1
    - rhash 1.4.6 hb9d3cd8_1
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_5
    - libgomp 15.1.0 h767d61c_5
    - libstdcxx 15.1.0 h8f9b012_5
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - libstdcxx >=14
test:
  requires:
    - cmake
    - gxx_linux-64 14.*
    - ninja
  files:
    - test/*
  commands:
    - test -f "${PREFIX}/include/simdjson.h"
    - test -f "${PREFIX}/lib/libsimdjson${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/cmake/simdjson/simdjson-config.cmake"
    - cmake -G Ninja -S test/ -B build/ -D TEST_TARGET=simdjson ${CMAKE_ARGS}
    - cmake --build build/
    - cmake --build build --target test
about:
  home: https://simdjson.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Parsing gigabytes of JSON per second
  description: 'JSON is everywhere on the Internet.

    Servers spend a *lot* of time parsing it. We need a fresh approach.

    The simdjson library uses commonly available SIMD instructions and

    microparallel algorithms to parse JSON 2.5x faster than anything else out there.

    '
  doc_url: https://simdjson.github.io/simdjson/
  dev_url: https://github.com/simdjson/simdjson/
extra:
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - elbaro
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250930.2.1
  remote_url: https://github.com/conda-forge/simdjson-feedstock
  sha: f40510719b42a311cd4b35351631d65e0ef097cd
