# This file created by conda-build 25.9.0
# ------------------------------------------------

package:
  name: libxml2
  version: 2.15.1
source:
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.15.1/libxml2-v2.15.1.tar.gz
  sha256: 0a5ebf8fa131585748d661ae692503483aff39d9b29b6c4b342cd80d422f246c
build:
  run_exports:
    - libxml2
    - libxml2-16 >=2.15.1
  number: 0
  string: h031cc0b_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - gcc_impl_linux-64 14.3.0 hd9e9e21_7
    - gcc_linux-64 14.3.0 h298d278_12
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libgcc 15.2.0 h767d61c_7
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_107
    - libgomp 15.2.0 h767d61c_7
    - libsanitizer 14.3.0 hd08acf3_7
    - libstdcxx 15.2.0 h8f9b012_7
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.2.0 h767d61c_7
    - libgomp 15.2.0 h767d61c_7
    - libiconv 1.18 h3b78370_2
    - liblzma 5.8.1 hb9d3cd8_2
    - liblzma-devel 5.8.1 hb9d3cd8_2
    - libxml2-16 2.15.1 hf2a90c1_0
    - libzlib 1.3.1 hb9d3cd8_2
    - zlib 1.3.1 hb9d3cd8_2
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - libiconv >=1.18,<2.0a0
    - liblzma >=5.8.1,<6.0a0
    - libxml2-16 2.15.1 hf2a90c1_0
    - libzlib >=1.3.1,<2.0a0
  run_constrained:
    - icu <0.0a0
test:
  requires:
    - ripgrep
  files:
    - test.xml
    - test_catalog.xml
  commands:
    - echo on
    - xmllint test.xml
    - mkdir -p "${PREFIX}/etc/xml"
    - cp   test_catalog.xml "${PREFIX}/etc/xml/catalog"
    - xmlcatalog "" "http://www.w3.org/2001/xml.xsd" | grep -x -F -e "file://test-uri-override"
    - rm  "${PREFIX}/etc/xml/catalog"
    - xmlcatalog "" "test-id" | grep -x -F -e "No entry for URI test-id"
    - xmlcatalog "test_catalog.xml" "test-id" | grep -x -F -e "file://test-uri"
    - export XML_CATALOG_FILES="file://$(pwd)/test_catalog.xml"
    - xmlcatalog "" "test-id" | grep -x -F -e "file://test-uri"
    - xmlcatalog "" "http://www.w3.org/2009/01/xml.xsd" | grep -x -F -e "No entry
      for URI http://www.w3.org/2009/01/xml.xsd"
about:
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
  description: 'Though libxml2 is written in C a variety of language

    bindings make it available in other environments.

    '
  doc_url: http://xmlsoft.org/html/index.html
  doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/devhelp/index.html
  dev_url: https://git.gnome.org/browse/libxml2/
extra:
  feedstock-name: libxml2
  recipe-maintainers:
    - gillins
    - isuruf
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
    - scopatz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251020.1.1
  remote_url: https://github.com/conda-forge/libxml2-feedstock
  sha: 2a67507d31d7b385dd7421e32e5aa8289bcc9a0e
