# This file created by conda-build 25.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 22 19:15:36 2025
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.18.16
source:
  url: https://pypi.org/packages/source/r/ruamel.yaml/ruamel.yaml-0.18.16.tar.gz
  sha256: a6e587512f3c998b2225d68aa1f35111c29fad14aed561a26e73fab729ec5e5a
build:
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/ruamel.yaml_1761160588389/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps -vv
  script_env:
    - RUAMEL_NO_LONG_DESCRIPTION=1
  string: py312h4c3975b_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - gcc_impl_linux-64 14.3.0 hd9e9e21_7
    - gcc_linux-64 14.3.0 h298d278_12
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libgcc 15.2.0 h767d61c_7
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_107
    - libgomp 15.2.0 h767d61c_7
    - libsanitizer 14.3.0 hd08acf3_7
    - libstdcxx 15.2.0 h8f9b012_7
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libexpat 2.7.1 hecca717_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - liblzma 5.8.1 hb9d3cd8_2
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.50.4 h0c1763c_0
    - libuuid 2.41.2 he9a06e4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.4 h26f9b46_0
    - pip 25.2 pyh8b19718_0
    - python 3.12.12 hfe2f287_0_cpython
    - python_abi 3.12 8_cp312
    - readline 8.2 h8c095d6_2
    - ruamel 1.0 py312h7900ff3_10
    - setuptools 80.9.0 pyhff2d567_0
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - wheel 0.45.1 pyhd8ed1ab_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - python >=3.12,<3.13.0a0
    - python_abi 3.12.* *_cp312
    - ruamel.yaml.clib >=0.1.2
test:
  imports:
    - ruamel.yaml
about:
  home: https://sourceforge.net/p/ruamel-yaml
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  recipe-maintainers:
    - davidbrochart
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251022.2.1
  remote_url: https://github.com/conda-forge/ruamel.yaml-feedstock
  sha: cf4a87792c2d63eaab8dfd3cc942c3e65867784f
