# This file created by conda-build 25.9.0
# ------------------------------------------------

package:
  name: libstdcxx-ng
  version: 15.2.0
source:
  - url:
      - https://ftp.gnu.org/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.gz
      - https://mirrors.ocf.berkeley.edu/gnu/gcc/gcc-15.2.0/gcc-15.2.0.tar.gz
    sha256: 7294d65cc1a0558cb815af0ca8c7763d86f7a31199794ede3f630c0d1b0a5723
    patches:
      - patches/0001-allow-commands-in-main-specfile.patch
      - patches/0002-patch-zoneinfo_dir_override-to-point-to-our-tzdata.patch
      - patches/0003-add-ldl-to-libstdc___la_LDFLAGS.patch
      - patches/0004-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
build:
  number: 7
  run_exports:
    strong:
      - libstdcxx
  string: h4852527_7
requirements:
  host:
    - libstdcxx 15.2.0 h8f9b012_7
  run:
    - libstdcxx 15.2.0 h8f9b012_7
test:
  commands:
    - echo "empty wrapper for compatibility with previous naming"
about:
  summary: The GNU C++ Runtime Library
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
extra:
  feedstock-name: ctng-compilers-feedstock
  recipe-maintainers:
    - beckermr
    - isuruf
    - timsnyder
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251008.2.1
  remote_url: https://github.com/conda-forge/ctng-compilers-feedstock
  sha: 75d69d32b4266eef9808c20157cc4af1ef9705ca
