# This file created by conda-build 25.9.0
# ------------------------------------------------

package:
  name: openssl
  version: 3.5.4
source:
  url: https://github.com/openssl/openssl/releases/download/openssl-3.5.4/openssl-3.5.4.tar.gz
  sha256: 967311f84955316969bdb1d8d4b983718ef42338639c621ec4c34fddef355e99
build:
  run_exports:
    - openssl >=3.5.4,<4.0a0
  number: 0
  string: h26f9b46_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - gcc_impl_linux-64 14.3.0 hd9e9e21_5
    - gcc_linux-64 14.3.0 h1382650_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libgcc 15.1.0 h767d61c_5
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_105
    - libgcc-ng 15.1.0 h69a702a_5
    - libgomp 15.1.0 h767d61c_5
    - libsanitizer 14.3.0 hd08acf3_5
    - libstdcxx 15.1.0 h8f9b012_5
    - libxcrypt 4.4.36 hd590300_1
    - make 4.4.1 hb9d3cd8_2
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  run:
    - __glibc >=2.17,<3.0.a0
    - ca-certificates
    - libgcc >=14
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_5
    - libgomp 15.1.0 h767d61c_5
test:
  requires:
    - pkg-config
    - ripgrep
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.5.4" openssl
    - if [[ "$(pkg-config --variable=prefix openssl)" == "" ]]; then exit 1; fi
about:
  home: https://www.openssl.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://docs.openssl.org/master/
extra:
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  feedstock-name: openssl
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251001.9.1
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: c8d762864846b867fc26602c7ac99a8ba98da5bc
