# This file created by conda-build 25.9.0
# ------------------------------------------------

package:
  name: libarchive
  version: 3.8.2
source:
  url: https://github.com/libarchive/libarchive/archive/v3.8.2.tar.gz
  sha256: 97548897f06ed7f5cd847fc62a67420809dbbd9b45ec13a25d3290fafba046c8
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
build:
  string: gpl_h7be2006_100
  run_exports:
    - libarchive >=3.8.2,<3.9.0a0
  number: 100
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.72 pl5321hbb4ee43_1
    - automake 1.17 pl5321ha770c72_0
    - binutils_impl_linux-64 2.44 hdf8817f_2
    - binutils_linux-64 2.44 h4852527_2
    - gcc_impl_linux-64 14.3.0 hd9e9e21_7
    - gcc_linux-64 14.3.0 h298d278_12
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 ha97dd6f_2
    - libgcc 15.2.0 h767d61c_7
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_107
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - libltdl 2.4.3a h5888daf_0
    - libsanitizer 14.3.0 hd08acf3_7
    - libstdcxx 15.2.0 h8f9b012_7
    - libtool 2.5.4 h5888daf_0
    - libxcrypt 4.4.36 hd590300_1
    - m4 1.4.20 hb9d3cd8_0
    - make 4.4.1 hb9d3cd8_2
    - perl 5.32.1 7_hd590300_perl5
    - pkg-config 0.29.2 h4bc722e_1009
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hda65f42_8
    - ca-certificates 2025.10.5 hbd8a1cb_0
    - icu 75.1 he02047a_0
    - libgcc 15.2.0 h767d61c_7
    - libgcc-ng 15.2.0 h69a702a_7
    - libgomp 15.2.0 h767d61c_7
    - libiconv 1.18 h3b78370_2
    - liblzma 5.8.1 hb9d3cd8_2
    - liblzma-devel 5.8.1 hb9d3cd8_2
    - libstdcxx 15.2.0 h8f9b012_7
    - libstdcxx-ng 15.2.0 h4852527_7
    - libxml2 2.14.6 h26afc86_2
    - libxml2-16 2.14.6 ha9997c6_2
    - libxml2-devel 2.14.6 h26afc86_2
    - libzlib 1.3.1 hb9d3cd8_2
    - lz4-c 1.10.0 h5888daf_1
    - lzo 2.10 h280c20c_1002
    - openssl 3.5.4 h26f9b46_0
    - zlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - __glibc >=2.17,<3.0.a0
    - bzip2 >=1.0.8,<2.0a0
    - libgcc >=14
    - liblzma >=5.8.1,<6.0a0
    - libxml2
    - libxml2-16 >=2.14.6
    - libzlib >=1.3.1,<2.0a0
    - lz4-c >=1.10.0,<1.11.0a0
    - lzo >=2.10,<3.0a0
    - openssl >=3.5.4,<4.0a0
    - zstd >=1.5.7,<1.6.0a0
test:
  files:
    - test/hello_world.xar
  commands:
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"
    - test -f "${PREFIX}/include/archive.h"
    - test -f "${PREFIX}/include/archive_entry.h"
    - test -f "${PREFIX}/lib/libarchive.a"
    - test -f "${PREFIX}/lib/libarchive${SHLIB_EXT}"
    - bsdcat --version
    - bsdcpio --version
    - bsdtar --version
    - bsdtar -tf test/hello_world.xar
about:
  home: http://www.libarchive.org/
  summary: Multi-format archive and compression library
  license: BSD-2-Clause
  license_file: COPYING
  license_family: BSD
extra:
  recipe-maintainers:
    - jakirkham
    - jjerphan
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251016.1.1
  remote_url: https://github.com/conda-forge/libarchive-feedstock
  sha: 3d502acb0e089b9f387db3e763bca21747ea326f
